item{
    id: 1
    name: 'Tesoura'
}
item{
    id: 2
    name: 'Cola'
}
item{
    id: 3
    name: 'Parafuso'
}
item{
    id: 7
    name: 'Pregador'
}
item{
    id: 9
    name: 'MicroSD'
}
item{
    id: 10
    name: 'Carta'
}
item{
    id: 11
    name: 'Pilha'
}
